# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: CI/CD for Spring Boot App with Maven

# on -> defines the event that triggers the workflow
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  # build-test -> defines the job name/ID
  build-test:
    permissions: write-all # allows the action to write to the repository (need it to update dependency graph)
    runs-on: ubuntu-latest

    steps:  # defines the sequence of tasks that the job will execute, actions to run, or linux commands to run
    - uses: actions/checkout@v4  # uses:  -> selects an action to run

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Execute Tests
      run: mvn -B test --file pom.xml

    - name: Build the app
      run: mvn -B package -DskipTests --file pom.xml

    # Run a shell command to create a curr date variable
    - name: Get current date (Docker image tag)
      id: date
      run: |
        datetime=$(date -u +'%Y%m%d%H%M%S.%3N')
        echo "::set-output name=datetime::$datetime"

    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        # secrets are stored in the GitHub repository settings
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        tags: ${{ steps.date.outputs.date }}
        image: ${{ secrets.DOCKERHUB_USERNAME }}/ci-cd-spring-github-actions
        registry: docker.io
        dockerfile: Dockerfile

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
